version: "3"

services:
  ubuntu:
    container_name: ubuntu
    image: psyoblade/data-engineer-ubuntu:20.04
    restart: always
    tty: true
    volumes:
      - ./ubuntu/example:/example

networks:
  default:
    name: default_network

