version: "3"
services:
  fluentd:
    container_name: fluentd
    image: psyoblade/data-engineer-intermediate-day2-fluentd
    user: root
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
